version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run: echo "hello world" # run the `echo` command
      - run: docker-compose -f docker-compose.ci.yml build app
      - run: docker-compose -f docker-compose.ci.yml up -d app
      - run: docker-compose -f docker-compose.ci.yml exec app ls -la
      - run: docker-compose -f docker-compose.ci.yml exec app bundle
      - run: docker-compose -f docker-compose.ci.yml down
